# Generated by Django 5.2.15 on 2026-06-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
